document:
  name: Linee guida per la qualità delle competenze digitali nelle professionalità ICT
  description: |
    Le Linee guida sulle professioni ICT contengono importanti novità normative
    e tecniche, tra cui i nuovi profili dedicati alle professionalità ICT nel
    settore dell’informazione geografica e una mappatura delle terminologie
    utilizzate per i profili. Obiettivo delle linee guida è anche garantire una
    continuità evolutiva delle professionalità ICT ed il contesto di
    applicazione rispetto agli esistenti manuali operativi AGID.
  tags:
    - competenze digitali
    - linee guida